development: &default
  adapter: postgresql
  database: slack_itc_autoingestion_development
  host: localhost
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: slack_itc_autoingestion_test
